// Code generated by "stringer -type=Kind"; DO NOT EDIT

package templates

import "fmt"

const _Kind_name = "TextExpressionUnescapedExpCode"

var _Kind_index = [...]uint8{0, 4, 14, 26, 30}

func (i kind) String() string {
	if i >= kind(len(_Kind_index)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
